name: Ubuntu 18.04

on:
  push:
    tags:
      - "*"

jobs:
  build-ubuntu18:
    name: Ubuntu 18.04
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y libboost1.65 libboost-all-dev python3-pip python3.7-dev libleveldb-dev
          sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 2
          sudo update-alternatives --config python3
          pip3 install .

      - name: Clone bmorecoin Release
        run: |
          git clone https://github.com/BMoreToken/bmorecoin/releases/download/v1.0.0-beta/ccx-cli-ubuntu-1804-vv1.0.0-beta.tar.gz
          tar -xvf ccx-cli-ubuntu-1804-vv1.0.0-beta.tar.gz

      - name: Build
        id: build
        run: |
          ccx_version=$(echo "$GITHUB_REF" | sed 's|refs/tags/||')
          release_name=ccx-desktop-ubuntu-1804-v"$ccx_version"   
          build_folder="build/release"
          
          python3 setup.py
          
          
          mkdir $release_name
          mv $build_folder/bmorecoin $release_name
          tar -czf "$release_name".tar.gz "$release_name"
          sha256=$(shasum -a 256 "$release_name".tar.gz | awk '{print toupper($1)}')

          echo "::set-output name=sha256::${sha256}"
          echo "::set-output name=release_name::${release_name}.tar.gz"
          echo "::set-output name=ccx_version::${ccx_version}"

      # since https://github.com/softprops/action-gh-release/pull/145 body is replaced instead of being appended
      # use v0.1.12 for now
      - name: Create Release
        uses: softprops/action-gh-release@v0.1.12
        with:
          files: ${{ steps.build.outputs.release_name }}
          name: BMoreCoin ElectrumX Server ${{ steps.build.outputs.ccx_version }}
          body: |
            [Download for Ubuntu 18.04](../../releases/download/${{ steps.build.outputs.ccx_version }}/${{ steps.build.outputs.release_name }}) **${{ steps.build.outputs.release_name }}**
            `SHA256 : ${{ steps.build.outputs.sha256 }}`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
